"""User Model Update 2

Revision ID: e7d644d292f8
Revises: 14566ce5dfb3
Create Date: 2020-04-24 08:47:50.172940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d644d292f8'
down_revision = '14566ce5dfb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastDisconnect', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastDisconnect')
    # ### end Alembic commands ###
